-- NEW, mapper-derived empty LOCAL Oracle schema, not an existing-production migration.
-- Apply only to an explicitly created empty disposable schema. No real records.
CREATE TABLE MEMBER (IDX NUMBER PRIMARY KEY,PARENT_IDX NUMBER,ID VARCHAR2(100) UNIQUE NOT NULL,PWD VARCHAR2(255) NOT NULL,NAME VARCHAR2(100),PHONE VARCHAR2(30),JUMIN VARCHAR2(30),ADDR VARCHAR2(500),ADDR_GPS VARCHAR2(100),MMS_CHK CHAR(1) DEFAULT 'N',JOINDATE DATE DEFAULT SYSDATE,LOGINDATE DATE,ID_SESSIONK VARCHAR2(200),ID_SESSIONL DATE,ID_IMG CHAR(1) DEFAULT 'N',GENDER VARCHAR2(10),HEIGHT NUMBER,WEIGHT NUMBER,B_TYPE VARCHAR2(10),POINT NUMBER DEFAULT 0 NOT NULL CHECK(POINT>=0),DEL_CHK CHAR(1) DEFAULT '0' CHECK(DEL_CHK IN('0','1')));
CREATE SEQUENCE SEQ_MEMBER_IDX START WITH 100;
CREATE TABLE HOSPITAL(H_IDX NUMBER PRIMARY KEY,HOSP VARCHAR2(200) NOT NULL,TEL VARCHAR2(40),MAJOR VARCHAR2(200),ADDR VARCHAR2(500),ADDR_GPS VARCHAR2(100),ONHOUR VARCHAR2(4),OFFHOUR VARCHAR2(4),INTERVALL VARCHAR2(4),MEAL_TIME VARCHAR2(4),H_COMM VARCHAR2(4000),DOC_COMM VARCHAR2(4000),REG_CHK CHAR(1) DEFAULT 'Y',DEL_CHK CHAR(1) DEFAULT '0');
CREATE SEQUENCE HOSPITAL_SEQ START WITH 100;
CREATE TABLE RESERVATION(NUM NUMBER PRIMARY KEY,H_IDX NUMBER NOT NULL REFERENCES HOSPITAL(H_IDX),ID VARCHAR2(100) NOT NULL REFERENCES MEMBER(ID),CURED VARCHAR2(200),RESERV1 VARCHAR2(10) NOT NULL,RESERV2 VARCHAR2(5) NOT NULL,DEL_CHK CHAR(1) DEFAULT 'B' CHECK(DEL_CHK IN('A','B','C')),STATE VARCHAR2(20) DEFAULT '미완료');
CREATE SEQUENCE RESERV_SEQ START WITH 100;
CREATE UNIQUE INDEX RESERV_ACTIVE_SLOT ON RESERVATION(CASE WHEN DEL_CHK='B' THEN H_IDX END,CASE WHEN DEL_CHK='B' THEN RESERV1 END,CASE WHEN DEL_CHK='B' THEN RESERV2 END);
CREATE UNIQUE INDEX RESERV_ACTIVE_MEMBER_HOSP ON RESERVATION(CASE WHEN DEL_CHK='B' THEN ID END,CASE WHEN DEL_CHK='B' THEN H_IDX END);
CREATE TABLE RATING(NUM NUMBER PRIMARY KEY REFERENCES RESERVATION(NUM),H_IDX NUMBER REFERENCES HOSPITAL(H_IDX),ID VARCHAR2(100) REFERENCES MEMBER(ID),RATE1 NUMBER CHECK(RATE1 BETWEEN 1 AND 5),RATE2 NUMBER CHECK(RATE2 BETWEEN 1 AND 5),RATE3 NUMBER CHECK(RATE3 BETWEEN 1 AND 5),RATE4 NUMBER CHECK(RATE4 BETWEEN 1 AND 5),COMM VARCHAR2(2000),REG DATE DEFAULT SYSDATE,DEL_CHK CHAR(1) DEFAULT '0');
CREATE TABLE FAV(ID VARCHAR2(100) REFERENCES MEMBER(ID),H_IDX NUMBER REFERENCES HOSPITAL(H_IDX),PRIMARY KEY(ID,H_IDX));
CREATE TABLE NOTICE(IDX NUMBER PRIMARY KEY,TITLE VARCHAR2(500),CONTENT CLOB,HITS NUMBER DEFAULT 0,REG DATE DEFAULT SYSDATE,DEL_CHK NUMBER DEFAULT 0);
CREATE SEQUENCE SEQ_NOTICE_IDX START WITH 100;
CREATE TABLE FAQ(IDX NUMBER PRIMARY KEY,Q VARCHAR2(1000),A CLOB,DEL_CHK NUMBER DEFAULT 0);
CREATE SEQUENCE SEQ_FAQ_IDX START WITH 100;
CREATE TABLE QNA(IDX NUMBER,CHK NUMBER CHECK(CHK IN(0,1)),ID VARCHAR2(100) REFERENCES MEMBER(ID),TITLE VARCHAR2(500),CONTENT CLOB,REG DATE DEFAULT SYSDATE,DEL_CHK NUMBER DEFAULT 0,PRIMARY KEY(IDX,CHK));
CREATE SEQUENCE SEQ_QNA_IDX START WITH 100;
CREATE TABLE FILES(F_IDX NUMBER PRIMARY KEY,IDX NUMBER REFERENCES NOTICE(IDX),ORG_FILE VARCHAR2(255),SAVE_FILE VARCHAR2(255),FILE_SIZE NUMBER,DEL_CHK CHAR(1) DEFAULT 'N');
CREATE SEQUENCE SEQ_FILE_IDX START WITH 100;
CREATE TABLE DRHER_RESET_TOKEN(TOKEN_HASH VARCHAR2(64) PRIMARY KEY,ID VARCHAR2(100) REFERENCES MEMBER(ID),EXPIRES_AT DATE NOT NULL,USED NUMBER DEFAULT 0 CHECK(USED IN(0,1)));
INSERT INTO HOSPITAL(H_IDX,HOSP,TEL,MAJOR,ADDR,ADDR_GPS,ONHOUR,OFFHOUR,INTERVALL,MEAL_TIME) VALUES(1,'합성 햇살내과','000-0000-0000','내과','합성 주소','37.5665,126.9780','0900','1800','30','1200');
INSERT INTO NOTICE(IDX,TITLE,CONTENT) VALUES(1,'로컬 합성 환경','실제 진료 예약 및 결제는 하지 않습니다.');
INSERT INTO FAQ(IDX,Q,A) VALUES(1,'예약 취소 방법','진료 30분 전까지 내 예약에서 취소합니다.');
COMMIT;
-- Accounts are created by POST /member/register with an operator-selected local password.
-- To create the local administrator, use the reserved ID admin only during isolated setup;
-- public registration explicitly rejects it. See seed-account.sql.example.
