package hp.common.security;
import org.junit.*;import static org.junit.Assert.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.net.*;import java.io.*;import java.util.*;import org.apache.catalina.startup.Tomcat;import org.apache.catalina.Context;import org.springframework.web.context.WebApplicationContext;import org.springframework.jdbc.core.JdbcTemplate;import javax.sql.DataSource;
/** Ephemeral loopback Tomcat using actual web.xml, Spring contexts and compiled JSPs. No browser or provider calls. */
public class NativeHttpSmokeTest {
 @Test public void nativeRegistrationJspAndKoreanPost()throws Exception {
  Path root=Files.createTempDirectory("hospital-http-");Path app=root.resolve("webapp");Files.createDirectories(app);
  try(java.util.stream.Stream<Path> paths=Files.walk(Paths.get("src/main/webapp"))){paths.forEach(p->{try{Path target=app.resolve(Paths.get("src/main/webapp").relativize(p));if(Files.isDirectory(p))Files.createDirectories(target);else Files.copy(p,target);}catch(IOException e){throw new UncheckedIOException(e);}});}
  Path xml=app.resolve("WEB-INF/web.xml");String web=new String(Files.readAllBytes(xml),StandardCharsets.UTF_8).replace("classpath*:config/spring/context-*.xml","classpath*:config/spring/context-*.xml classpath:native-context.xml");Files.write(xml,web.getBytes(StandardCharsets.UTF_8));
  Tomcat tomcat=new Tomcat();tomcat.setBaseDir(root.resolve("tomcat").toString());tomcat.setPort(0);tomcat.getConnector().setProperty("address","127.0.0.1");Context context=tomcat.addWebapp("/hospital",app.toString());context.setParentClassLoader(getClass().getClassLoader());
  try{tomcat.start();assertTrue(context.getState().isAvailable());WebApplicationContext spring=(WebApplicationContext)context.getServletContext().getAttribute(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE);JdbcTemplate jdbc=new JdbcTemplate(spring.getBean("dataSource",DataSource.class));jdbc.execute("DROP ALL OBJECTS");String ddl=new String(Files.readAllBytes(Paths.get("local-db/oracle-local.sql")),StandardCharsets.UTF_8);for(String statement:ddl.split(";")){String cleaned=statement.replaceAll("(?m)--[^\\n]*", "").trim();if(cleaned.startsWith("CREATE TABLE MEMBER")||cleaned.startsWith("CREATE SEQUENCE SEQ_MEMBER_IDX"))jdbc.execute(cleaned);}
   String base="http://127.0.0.1:"+tomcat.getConnector().getLocalPort()+"/hospital";HttpURLConnection get=(HttpURLConnection)new URL(base+"/member/register").openConnection();get.setConnectTimeout(5000);get.setReadTimeout(5000);assertEquals(200,get.getResponseCode());String body=read(get.getInputStream());assertTrue(body.contains("회원가입"));String csrf=get.getHeaderField("X-CSRF-Token");String cookie="";for(Map.Entry<String,List<String>> h:get.getHeaderFields().entrySet())if(h.getKey()!=null&&h.getKey().equalsIgnoreCase("Set-Cookie"))for(String c:h.getValue())cookie+=c.split(";",2)[0]+"; ";get.disconnect();
   String encoded="_csrf="+URLEncoder.encode(csrf,"UTF-8")+"&ID=smoke-patient&PWD=SmokePassword123%21&NAME="+URLEncoder.encode("한글 환자","UTF-8")+"&ADDR="+URLEncoder.encode("서울 합성 주소","UTF-8")+"&PHONE=000&ADDR_GPS=37.5%2C127&MMS_CHK=N";
   HttpURLConnection post=(HttpURLConnection)new URL(base+"/member/register").openConnection();post.setInstanceFollowRedirects(false);post.setRequestMethod("POST");post.setDoOutput(true);post.setRequestProperty("Cookie",cookie);post.setRequestProperty("Content-Type","application/x-www-form-urlencoded");post.setConnectTimeout(5000);post.setReadTimeout(5000);post.getOutputStream().write(encoded.getBytes(StandardCharsets.UTF_8));assertEquals(302,post.getResponseCode());post.disconnect();assertEquals("한글 환자",jdbc.queryForObject("SELECT NAME FROM MEMBER WHERE ID='smoke-patient'",String.class));assertTrue(PasswordHash.verify("SmokePassword123!",jdbc.queryForObject("SELECT PWD FROM MEMBER WHERE ID='smoke-patient'",String.class)));
  } finally {tomcat.stop();tomcat.destroy();try(java.util.stream.Stream<Path> paths=Files.walk(root)){paths.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(IOException ignored){}});}}
 }
 private static String read(InputStream in)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return new String(out.toByteArray(),StandardCharsets.UTF_8);}
}
