package hp.common.security;
import org.junit.*;import static org.junit.Assert.*;import java.util.*;import java.lang.reflect.*;import java.time.*;
import org.h2.jdbcx.JdbcDataSource;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;import org.springframework.transaction.support.TransactionTemplate;import org.springframework.core.io.ClassPathResource;import org.mybatis.spring.*;import org.springframework.mock.web.MockHttpSession;import org.springframework.ui.ExtendedModelMap;
import hp.Final.dao.*;import hp.Final.service.*;
/** Executes original MyBatis statements against isolated Oracle-mode H2, not an operational Oracle claim. */
public class NativeTransactionTest {
 JdbcTemplate jdbc;SqlSessionTemplate nativeSql;TransactionTemplate tx;ReservServiceImpl reservations;RateServiceImpl ratings;MockHttpSession session;
 static void set(Object target,Class<?> type,String key,Object value)throws Exception{Field f=type.getDeclaredField(key);f.setAccessible(true);f.set(target,value);}
 @Before public void setup()throws Exception{JdbcDataSource ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:"+UUID.randomUUID()+";MODE=Oracle;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000");jdbc=new JdbcTemplate(ds);tx=new TransactionTemplate(new DataSourceTransactionManager(ds));
 jdbc.execute("CREATE TABLE MEMBER(ID VARCHAR2(100) PRIMARY KEY,IDX NUMBER,POINT NUMBER CHECK(POINT>=0),PWD VARCHAR2(255),DEL_CHK VARCHAR2(1))");jdbc.execute("CREATE TABLE HOSPITAL(H_IDX NUMBER PRIMARY KEY,HOSP VARCHAR2(100),MAJOR VARCHAR2(40),ONHOUR VARCHAR2(4),OFFHOUR VARCHAR2(4),INTERVALL VARCHAR2(3),MEAL_TIME VARCHAR2(4),REG_CHK VARCHAR2(1))");jdbc.execute("CREATE SEQUENCE RESERV_SEQ START WITH 10");jdbc.execute("CREATE TABLE RESERVATION(NUM NUMBER PRIMARY KEY,H_IDX NUMBER,ID VARCHAR2(100),CURED VARCHAR2(40),RESERV1 VARCHAR2(10),RESERV2 VARCHAR2(5),DEL_CHK VARCHAR2(1),STATE VARCHAR2(20))");jdbc.execute("CREATE TABLE RATING(H_IDX NUMBER,ID VARCHAR2(100),RATE1 NUMBER,RATE2 NUMBER,RATE3 NUMBER,RATE4 NUMBER,COMM VARCHAR2(2000),REG DATE,NUM NUMBER UNIQUE)");jdbc.execute("INSERT INTO MEMBER VALUES('owner',1,500,'unconfigured','0')");jdbc.execute("INSERT INTO HOSPITAL VALUES(1,'Synthetic','Internal','0900','1800','30','1200','Y')");
 SqlSessionFactoryBean factory=new SqlSessionFactoryBean();factory.setDataSource(ds);factory.setMapperLocations(new org.springframework.core.io.Resource[]{new ClassPathResource("mapper/common/Common_SQL.xml"),new ClassPathResource("mapper/sy/reserv_SQL.xml"),new ClassPathResource("mapper/sy/mypage_SQL.xml"),new ClassPathResource("mapper/sy/rate_SQL.xml"),new ClassPathResource("mapper/common/secure_SQL.xml"),new ClassPathResource("mapper/sk/member_SQL.xml")});SqlSessionTemplate sql=new SqlSessionTemplate(factory.getObject());nativeSql=sql;ReservDAO rd=new ReservDAO();MypageDAO md=new MypageDAO();RateDAO rate=new RateDAO();for(Object d:new Object[]{rd,md,rate})set(d,hp.common.dao.AbstractDAO.class,"sqlSession",sql);reservations=new ReservServiceImpl();set(reservations,ReservServiceImpl.class,"reservDAO",rd);set(reservations,ReservServiceImpl.class,"mypageDAO",md);ratings=new RateServiceImpl();set(ratings,RateServiceImpl.class,"rateDao",rate);session=new MockHttpSession();session.setAttribute("ID","owner");session.setAttribute("IDX",1);
 }
 Map<String,Object> booking(){Map<String,Object> p=new HashMap<String,Object>();p.put("H_IDX","1");p.put("CURED","Internal");p.put("RESERV1",LocalDate.now().plusDays(1).toString().replace('-','/'));p.put("RESERV2","09:00");return p;}
 int book(){return tx.execute(s->{try{return reservations.insertReserv(booking(),new ExtendedModelMap(),session);}catch(Exception e){throw new RuntimeException(e);}});}
 @Test public void bookingRetryCancelRetryAndBalance(){assertEquals(0,book());assertEquals(0,book());assertEquals(Integer.valueOf(400),jdbc.queryForObject("SELECT POINT FROM MEMBER",Integer.class));assertEquals(Integer.valueOf(1),jdbc.queryForObject("SELECT COUNT(*) FROM RESERVATION",Integer.class));tx.execute(s->{try{reservations.cancelReserv(booking(),session);reservations.cancelReserv(booking(),session);}catch(Exception e){throw new RuntimeException(e);}return null;});assertEquals(Integer.valueOf(500),jdbc.queryForObject("SELECT POINT FROM MEMBER",Integer.class));}
 @Test public void failureRollsBackDebit(){jdbc.execute("DROP SEQUENCE RESERV_SEQ");try{book();fail();}catch(RuntimeException expected){}assertEquals(Integer.valueOf(500),jdbc.queryForObject("SELECT POINT FROM MEMBER",Integer.class));}
 @Test public void ratingOwnershipRangeAndAtomicRollback()throws Exception{jdbc.execute("INSERT INTO RESERVATION VALUES(1,1,'owner','Internal','2026/01/01','09:00','A','미완료')");Map<String,Object> p=new HashMap<String,Object>();p.put("NUM",1);p.put("H_IDX",999);p.put("ID","intruder");p.put("COMM","Synthetic review");for(int i=1;i<=4;i++)p.put("RATE"+i,5);try{ratings.insertRating(p);fail();}catch(SecurityException expected){}p.put("ID","owner");p.put("RATE1",6);try{ratings.insertRating(p);fail();}catch(IllegalArgumentException expected){}p.put("RATE1",5);try{tx.execute(s->{try{ratings.insertRating(p);throw new IllegalStateException("simulate downstream failure");}catch(Exception e){throw new RuntimeException(e);}});fail();}catch(RuntimeException expected){}assertEquals(Integer.valueOf(0),jdbc.queryForObject("SELECT COUNT(*) FROM RATING",Integer.class));assertEquals("미완료",jdbc.queryForObject("SELECT STATE FROM RESERVATION",String.class));}
 @Test public void ratingCommitIsOwnedAndSingleUse()throws Exception{jdbc.execute("INSERT INTO RESERVATION VALUES(2,1,'owner','Internal','2026/01/01','09:00','A','미완료')");Map<String,Object> p=new HashMap<String,Object>();p.put("NUM",2);p.put("ID","owner");p.put("COMM","Synthetic review");for(int i=1;i<=4;i++)p.put("RATE"+i,4);tx.execute(s->{try{ratings.insertRating(p);}catch(Exception e){throw new RuntimeException(e);}return null;});assertEquals(Integer.valueOf(1),jdbc.queryForObject("SELECT COUNT(*) FROM RATING",Integer.class));assertEquals(Integer.valueOf(1),jdbc.queryForObject("SELECT H_IDX FROM RATING",Integer.class));try{ratings.insertRating(p);fail();}catch(SecurityException expected){}}
 @Test public void concurrentLastSlotAllowsOneOwner()throws Exception {jdbc.execute("INSERT INTO MEMBER VALUES('second',2,500,'unconfigured','0')");java.util.concurrent.ExecutorService pool=java.util.concurrent.Executors.newFixedThreadPool(2);java.util.concurrent.CountDownLatch start=new java.util.concurrent.CountDownLatch(1);java.util.List<java.util.concurrent.Future<Boolean>> futures=new ArrayList<java.util.concurrent.Future<Boolean>>();for(String id:new String[]{"owner","second"}){final String member=id;futures.add(pool.submit(()->{start.await();MockHttpSession ses=new MockHttpSession();ses.setAttribute("ID",member);ses.setAttribute("IDX",member.equals("owner")?1:2);try{return tx.execute(status->{try{return reservations.insertReserv(booking(),new ExtendedModelMap(),ses)==0;}catch(Exception e){throw new RuntimeException(e);}});}catch(RuntimeException expected){return false;}}));}start.countDown();int successes=0;for(java.util.concurrent.Future<Boolean> f:futures)if(f.get())successes++;pool.shutdownNow();assertEquals(1,successes);assertEquals(Integer.valueOf(1),jdbc.queryForObject("SELECT COUNT(*) FROM RESERVATION",Integer.class));assertEquals(Integer.valueOf(900),jdbc.queryForObject("SELECT SUM(POINT) FROM MEMBER",Integer.class));}
 @Test public void nativeResetConsumesTokenOnlyAfterPasswordWrite()throws Exception {jdbc.execute("CREATE TABLE DRHER_RESET_TOKEN(TOKEN_HASH VARCHAR2(64) PRIMARY KEY,ID VARCHAR2(100),EXPIRES_AT DATE,USED NUMBER)");String token="synthetic-one-use-token";String hash=java.util.Base64.getEncoder().encodeToString(java.security.MessageDigest.getInstance("SHA-256").digest(token.getBytes(java.nio.charset.StandardCharsets.UTF_8)));jdbc.update("INSERT INTO DRHER_RESET_TOKEN VALUES(?,?,DATEADD('MINUTE',15,CURRENT_TIMESTAMP),0)",hash,"owner");hp.common.controller.PasswordResetController controller=new hp.common.controller.PasswordResetController();hp.common.service.PasswordResetServiceImpl service=new hp.common.service.PasswordResetServiceImpl();set(service,hp.common.service.PasswordResetServiceImpl.class,"sql",nativeSql);set(controller,hp.common.controller.PasswordResetController.class,"service",service);try{tx.execute(s->{try{return controller.confirm(token,"short",new MockHttpSession());}catch(Exception e){throw new RuntimeException(e);}});fail();}catch(RuntimeException expected){}assertEquals(Integer.valueOf(0),jdbc.queryForObject("SELECT USED FROM DRHER_RESET_TOKEN",Integer.class));tx.execute(s->{try{return controller.confirm(token,"NewPassword123!",new MockHttpSession());}catch(Exception e){throw new RuntimeException(e);}});assertEquals(Integer.valueOf(1),jdbc.queryForObject("SELECT USED FROM DRHER_RESET_TOKEN",Integer.class));assertTrue(PasswordHash.verify("NewPassword123!",jdbc.queryForObject("SELECT PWD FROM MEMBER",String.class)));try{controller.confirm(token,"NewPassword123!",new MockHttpSession());fail();}catch(SecurityException expected){}}
}
