package hp.common.security;
import org.junit.*;import static org.junit.Assert.*;import java.util.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;
import org.springframework.web.context.support.XmlWebApplicationContext;import org.springframework.mock.web.*;import org.springframework.core.io.FileSystemResourceLoader;import org.springframework.aop.support.AopUtils;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;import javax.sql.DataSource;import hp.common.service.PasswordResetService;import hp.common.service.HospitalCatalogService;
public class NativeContextTest {
 XmlWebApplicationContext parent,child;JdbcTemplate jdbc;MockMvc mvc;
 @Before public void setup(){MockServletContext sc=new MockServletContext("src/main/webapp",new FileSystemResourceLoader());parent=new XmlWebApplicationContext();parent.setServletContext(sc);parent.setConfigLocations(new String[]{"classpath*:config/spring/context-*.xml","classpath:native-context.xml"});parent.refresh();child=new XmlWebApplicationContext();child.setParent(parent);child.setServletContext(sc);child.setConfigLocation("/WEB-INF/config/action-servlet.xml");child.refresh();jdbc=new JdbcTemplate(parent.getBean("dataSource",DataSource.class));jdbc.execute("DROP ALL OBJECTS");jdbc.execute("CREATE TABLE MEMBER(IDX NUMBER,ID VARCHAR2(100),PWD VARCHAR2(255),NAME VARCHAR2(100),ADDR VARCHAR2(200),ID_IMG VARCHAR2(1),DEL_CHK VARCHAR2(1))");jdbc.execute("CREATE TABLE DRHER_RESET_TOKEN(TOKEN_HASH VARCHAR2(64),ID VARCHAR2(100),EXPIRES_AT DATE,USED NUMBER CHECK(USED=0))");mvc=MockMvcBuilders.webAppContextSetup(child).addFilters(new RequestSecurityFilter()).build();}
 @After public void close(){if(child!=null)child.close();if(parent!=null)parent.close();}
 @Test public void actualContextProxiesResetAndRollsBackFailedConsume()throws Exception{PasswordResetService service=parent.getBean(PasswordResetService.class);assertTrue(AopUtils.isAopProxy(service));assertTrue(AopUtils.isAopProxy(parent.getBean(HospitalCatalogService.class)));jdbc.update("INSERT INTO MEMBER VALUES(1,'owner','previous','합성 환자','','N','0')");String token="context-token",hash=Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest(token.getBytes(StandardCharsets.UTF_8)));jdbc.update("INSERT INTO DRHER_RESET_TOKEN VALUES(?,?,DATEADD('MINUTE',15,CURRENT_TIMESTAMP),0)",hash,"owner");try{service.confirm(token,"ContextPassword123!");fail();}catch(RuntimeException expected){}assertEquals("previous",jdbc.queryForObject("SELECT PWD FROM MEMBER",String.class));}
 @Test public void dispatcherAccountViewAndKoreanFormIdentity()throws Exception{mvc.perform(get("/member/loginForm")).andExpect(status().isOk()).andExpect(view().name("compat/account"));MockHttpSession session=new MockHttpSession();session.setAttribute("CSRF","test-csrf");String password="ContextPassword123!";jdbc.update("INSERT INTO MEMBER VALUES(1,'patient',?,'합성 환자','서울','N','0')",PasswordHash.hash(password));MvcResult result=mvc.perform(post("/member/login").session(session).param("_csrf","test-csrf").param("ID","patient").param("PWD",password)).andExpect(status().is3xxRedirection()).andReturn();assertEquals("UTF-8",result.getRequest().getCharacterEncoding());assertEquals("합성 환자",result.getRequest().getSession().getAttribute("NAME"));}
}
