/* New compatibility implementation for omitted original controllers. Synthetic only.
 * Reuses DrHerMockBackend reservation/rating/search contracts; not recovered server code. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./mock-backend.js'));else root.DrHerModules=factory(root.DrHerMockBackend);})(typeof self!=='undefined'?self:this,function(MB){
'use strict';
const copy=x=>JSON.parse(JSON.stringify(x));
const routes={accounts:'/hospital/member/loginForm',register:'/hospital/member/register',recover:'/hospital/member/sendMail',profile:'/hospital/mypage/OpenMypageMain',points:'/hospital/mypage/paymentPoint',withdraw:'/hospital/mypage/deleteForm',notice:'/hospital/notice/NoticeList',faq:'/hospital/faq/FaqList',qna:'/hospital/qna/QnaList',admin:'/hospital/admin/adminMain',catalog:'/hospital/admin/catalog',guide:'/hospital/guide/searchGuide'};
function create({fixtures,store,now=()=>new Date(),random=()=>Math.random().toString(36).slice(2)}){
 const fx=copy(fixtures);let base;
 function save(s){store.save(s);}
 function state(){let s=store.load();if(!MB.isValidState(s))s=copy(fx.SEED_STATE);if(!Array.isArray(s.members)||!Array.isArray(s.catalog)||!Array.isArray(s.notice)||!Array.isArray(s.faq)||!Array.isArray(s.qna)||!Array.isArray(s.ledger)||!Array.isArray(s.outbox)||!Array.isArray(s.tokens)||!Array.isArray(s.audit)||!s.receipts){s.members=fx.MEMBER.map((m,i)=>({...m,IDX:m.IDX||i+1,ROLE:m.ID==='admin'?'admin':'member',PASSWORD:'DemoPass123!',POINT:m.ID===fx.SESSION.ID?s.POINT:500,ACTIVE:true}));if(!s.members.some(m=>m.ID==='admin'))s.members.push({ID:'admin',NAME:'가상 관리자',ROLE:'admin',PASSWORD:'DemoPass123!',POINT:0,ACTIVE:true});s.session=fx.SESSION.ID;s.expires=now().getTime()+3600000;s.catalog=copy(fx.HOSPITAL);s.notice=[{IDX:1,TITLE:'예약 이용 안내',CONTENTS:'예약에는 합성 포인트 100점이 사용됩니다. 실제 진료 예약이나 결제는 발생하지 않습니다.',files:[]}];s.faq=[{IDX:1,TITLE:'예약을 취소하면 포인트가 돌아오나요?',CONTENTS:'진료 30분 전까지 취소하면 합성 포인트가 반환됩니다.'}];s.qna=[];s.members.forEach(m=>{m.EMAIL=m.EMAIL||m.ID+'@example.invalid';});s.outbox=[];s.tokens=[];s.ledger=s.members.map(m=>({ID:m.ID,AMOUNT:m.POINT,REASON:'초기 합성 잔액',KEY:'seed:'+m.ID}));s.audit=[];s.receipts={};save(s);}if(!s.seedRatings){s.seedRatings=copy(fx.RATING).map((r,i)=>({...r,NUM:-(i+1)}));save(s);}return s;}
 function user(s=state(),required=true){const u=s.members.find(m=>m.ID===s.session&&m.ACTIVE);if(!u||s.expires<now().getTime()){if(required)throw Error('로그인 후 이용해주세요.');return null;}return u;}
 function admin(s){const u=user(s);if(u.ROLE!=='admin')throw Error('관리자 권한이 필요합니다.');return u;}
 function text(p,k,max=2000){const v=String(p[k]||'').trim();if(!v||v.length>max)throw Error(k+' 입력을 확인해주세요.');return v;}
 function record(s,u,amount,reason,key){if(s.ledger.some(l=>l.KEY===key))return;u.POINT+=amount;s.ledger.push({ID:u.ID,AMOUNT:amount,REASON:reason,KEY:key,AT:now().toISOString()});}
 function legacy(s,u){fx.HOSPITAL=s.catalog;fx.MEMBER=s.members;fx.RATING=s.seedRatings;s.POINT=u?u.POINT:0;const proxy={load:()=>copy(s),save:v=>{const members=s.members;Object.assign(s,v);s.members=members;if(u)u.POINT=v.POINT;save(s);}};return MB.createBackend({fixtures:fx,session:u||{ID:''},store:proxy,now});}
 function execute(action,p={}){let s=state(),u=user(s,false),result;const id=()=>String(p.IDX||p.NUM||'');
 if(action==='state')return {user:u?{...u,PASSWORD:undefined}:null,notice:s.notice,faq:s.faq,catalog:s.catalog,ledger:u?s.ledger.filter(l=>l.ID===u.ID):[],qna:u?s.qna.filter(q=>u.ROLE==='admin'||q.ID===u.ID):[],outbox:s.outbox,admin:u&&u.ROLE==='admin'?{members:s.members.map(m=>({...m,PASSWORD:undefined})),reservations:s.RESERVATION,ratings:s.seedRatings.concat(s.RATING||[]),audit:s.audit}:null};
 if(action==='reset'){store.save(copy(fx.SEED_STATE));return state();}
 if(action==='checkId')return {available:!s.members.some(m=>m.ID===String(p.ID))};
 if(action==='register'){const ID=text(p,'ID',80),PWD=text(p,'PWD',128);if(!/^[a-zA-Z0-9_.@-]{3,80}$/.test(ID)||PWD.length<10)throw Error('아이디 3자 이상, 비밀번호 10자 이상을 입력해주세요.');if(s.members.some(m=>m.ID===ID))throw Error('이미 등록된 아이디입니다.');s.members.push({ID,IDX:Math.max(...s.members.map(m=>Number(m.IDX)||0))+1,NAME:text(p,'NAME',60),EMAIL:text(p,'EMAIL',160),PASSWORD:PWD,ROLE:'member',POINT:0,ACTIVE:true});result={ok:true};}
 else if(action==='login'){u=s.members.find(m=>m.ID===p.ID&&m.PASSWORD===p.PWD&&m.ACTIVE);if(!u)throw Error('아이디 또는 비밀번호가 맞지 않습니다.');s.session=u.ID;s.expires=now().getTime()+3600000;result={ok:true};}
 else if(action==='logout'){s.session=null;result={ok:true};}
 else if(action==='recover'){const m=s.members.find(m=>m.ID===p.ID&&m.EMAIL===p.EMAIL&&m.ACTIVE);if(m){const token=random()+random();s.tokens.push({ID:m.ID,token,expires:now().getTime()+900000,used:false});s.outbox.push({TO:m.EMAIL,TOKEN:token,TEXT:'합성 비밀번호 재설정 링크 — 15분 동안 유효',AT:now().toISOString()});}result={ok:true,message:'일치하는 계정이 있으면 로컬 메일함에 링크가 생성됩니다.'};}
 else if(action==='resetPassword'){const t=s.tokens.find(t=>t.token===p.TOKEN&&!t.used&&t.expires>now().getTime());if(!t)throw Error('만료되었거나 이미 사용한 링크입니다.');const pwd=text(p,'PWD',128);if(pwd.length<10)throw Error('비밀번호는 10자 이상입니다.');s.members.find(m=>m.ID===t.ID).PASSWORD=pwd;t.used=true;if(s.session===t.ID)s.session=null;result={ok:true};}
 else if(action==='profile'){u=user(s);['NAME','PHONE','ADDR','HEIGHT','WEIGHT','B_TYPE'].forEach(k=>{if(p[k]!==undefined)u[k]=String(p[k]).trim().slice(0,200);});if(!u.NAME)throw Error('이름을 입력해주세요.');result={ok:true};}
 else if(action==='avatar'){u=user(s);if(p.DATA&&!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(p.DATA))throw Error('PNG 또는 JPEG 사진을 선택해주세요.');if(String(p.DATA||'').length>280000)throw Error('사진은 200KB 이하로 선택해주세요.');u.AVATAR=p.DATA||null;result={ok:true};}
 else if(action==='charge'){u=user(s);const n=Number(p.POINT),key=text(p,'KEY',100);if(!Number.isInteger(n)||n<100||n>10000)throw Error('100~10,000점 사이의 정수를 입력해주세요.');record(s,u,n,'합성 충전',u.ID+':charge:'+key);result={ok:true,POINT:u.POINT};}
 else if(action==='withdraw'){u=user(s);if(u.ROLE==='admin')throw Error('관리자 계정은 이 화면에서 탈퇴할 수 없습니다.');if(p.PWD!==u.PASSWORD)throw Error('현재 비밀번호를 확인해주세요.');if(s.RESERVATION.some(r=>r.ID===u.ID&&r.DEL_CHK==='B'))throw Error('예정된 예약을 먼저 취소해주세요.');u.ACTIVE=false;s.FAV=s.FAV.filter(f=>f.ID!==u.ID);s.session=null;result={ok:true};}
 else if(/^(notice|faq|qna)\.(save|delete|answer)$/.test(action)){const [kind,op]=action.split('.');u=kind==='qna'?user(s):admin(s);let item=s[kind].find(v=>String(v.IDX)===id());if(item&&kind==='qna'&&u.ROLE!=='admin'&&item.ID!==u.ID)throw Error('본인의 문의만 변경할 수 있습니다.');if(op==='delete'){if(!item)throw Error('삭제할 항목이 없습니다.');s[kind]=s[kind].filter(v=>v!==item);}else if(op==='answer'){admin(s);if(!item)throw Error('문의가 없습니다.');item.ANSWER=String(p.ANSWER||'').trim().slice(0,2000);}else{if(kind==='qna'&&item&&item.ANSWER)throw Error('답변된 문의는 수정할 수 없습니다.');const TITLE=text(p,'TITLE',160),CONTENTS=text(p,'CONTENTS',4000);if(!item){item={IDX:Math.max(0,...s[kind].map(v=>v.IDX))+1,ID:u.ID};s[kind].push(item);}Object.assign(item,{TITLE,CONTENTS});if(kind==='notice'&&p.FILE_REMOVE===true)item.files=[];if(kind==='notice'&&p.FILE_NAME){if(!/^[\w가-힣 .-]+\.txt$/.test(p.FILE_NAME)||String(p.FILE_TEXT||'').length>100000)throw Error('첨부는 100KB 이하의 텍스트 파일만 가능합니다.');item.files=[{NAME:p.FILE_NAME,TEXT:String(p.FILE_TEXT||'')}];}}result={ok:true};}
 else if(action==='catalog.save'){admin(s);let h=s.catalog.find(v=>String(v.H_IDX)===String(p.H_IDX));const values={HOSP:text(p,'HOSP',100),ADDR:text(p,'ADDR',200),TEL:text(p,'TEL',30),MAJOR:text(p,'MAJOR',100),ONHOUR:p.ONHOUR||'0900',OFFHOUR:p.OFFHOUR||'1800',INTERVALL:'30',MEAL_TIME:'1200',ADDR_GPS:p.ADDR_GPS||'37.5665,126.9780',REG_CHK:p.REG_CHK==='N'?'N':'Y',DEL_CHK:'0'};if(!/^\d{4}$/.test(values.ONHOUR)||!/^\d{4}$/.test(values.OFFHOUR)||Number(values.OFFHOUR)<=Number(values.ONHOUR)||!/^[-\d.]+,[-\d.]+$/.test(values.ADDR_GPS))throw Error('운영 시간과 좌표를 확인해주세요.');if(!h){h={H_IDX:Math.max(0,...s.catalog.map(h=>Number(h.H_IDX)))+1};s.catalog.push(h);}Object.assign(h,values);result={ok:true};}
 else if(action==='catalog.delete'){admin(s);const h=s.catalog.find(h=>String(h.H_IDX)===String(p.H_IDX));if(!h)throw Error('병원이 없습니다.');if(s.RESERVATION.some(r=>String(r.H_IDX)===String(p.H_IDX)&&r.DEL_CHK==='B'))throw Error('예정된 예약이 있어 삭제할 수 없습니다.');h.DEL_CHK='1';h.REG_CHK='N';s.FAV=s.FAV.filter(f=>String(f.H_IDX)!==String(p.H_IDX));result={ok:true};}
 else if(action==='admin.member'){admin(s);const m=s.members.find(m=>m.ID===p.ID);if(!m||m.ROLE==='admin')throw Error('변경할 수 없는 계정입니다.');if(p.NAME!==undefined)m.NAME=text(p,'NAME',60);if(p.PHONE!==undefined)m.PHONE=String(p.PHONE).slice(0,40);if(p.ADDR!==undefined)m.ADDR=String(p.ADDR).slice(0,200);if(p.ACTIVE!==undefined)m.ACTIVE=p.ACTIVE===true;if(!m.ACTIVE&&s.RESERVATION.some(r=>r.ID===m.ID&&r.DEL_CHK==='B'))throw Error('예정된 예약을 먼저 처리해주세요.');result={ok:true};}
 else if(action==='admin.reservation'){admin(s);const r=s.RESERVATION.find(r=>String(r.NUM)===id());if(!r||r.DEL_CHK!=='B'||!['A','C'].includes(p.STATUS))throw Error('유효한 예약에서만 상태를 변경할 수 있습니다.');r.DEL_CHK=p.STATUS;if(p.STATUS==='C'){const member=s.members.find(m=>m.ID===r.ID);record(s,member,100,'관리자 예약 취소','cancel:'+r.NUM);}result={ok:true};}
 else if(action==='admin.review'){admin(s);let r=(s.RATING||[]).concat(s.seedRatings).find(r=>String(r.NUM)===id());if(!r)throw Error('후기를 찾을 수 없습니다.');if(p.DELETE===true){s.RATING=s.RATING.filter(v=>v!==r);s.seedRatings=s.seedRatings.filter(v=>v!==r);const visit=s.RESERVATION.find(v=>v.NUM===r.NUM);if(visit)visit.STATE='미완료';}else r.COMM=text(p,'COMM',2000);result={ok:true};}
 else {if(!['search','detail','reviews','count','times'].includes(action))u=user(s);base=legacy(s,u);const before=u?u.POINT:0;switch(action){case 'search':result=base.selectBoardList({QUERY:'hplist.selectAllHpList',...p});if(p.LAT&&p.LON){result.list.forEach(h=>{if(h.LAT){const dlat=(+h.LAT-+p.LAT)*Math.PI/180,dlon=(+h.LON-+p.LON)*Math.PI/180;h.DISTANCE=Math.round(6371000*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(+p.LAT*Math.PI/180)*Math.cos(+h.LAT*Math.PI/180)*Math.sin(dlon/2)**2)));}});if(p.SORT==='distance')result.list.sort((a,b)=>(a.DISTANCE||Infinity)-(b.DISTANCE||Infinity));}break;case 'detail':result=base.selectHpDetail(p.H_IDX);break;case 'reviews':result=base.selectReview();break;case 'count':result=base.selectCount();break;case 'times':result=base.selectDate(p);break;case 'book':{const key=u.ID+':book:'+text(p,'KEY',100);if(s.receipts[key])return copy(s.receipts[key]);result=base.insertReserv(p);if(result.code===0)s.receipts[key]=result;break;}case 'cancel':result=base.cancelReserv(p);break;case 'reservations':result=base.selectReservation();break;case 'past':result=base.selectPastReservation();break;case 'ratingList':result=base.ratingList();break;case 'rate':result=base.insertRating(p);break;case 'favorites':result=base.selectFavList();break;case 'favorite':result=base.insertFav(p);break;case 'unfavorite':result=base.delFavHp(p);break;default:throw Error('알 수 없는 업무 요청입니다: '+action);}if(u&&u.POINT!==before)s.ledger.push({ID:u.ID,AMOUNT:u.POINT-before,REASON:action==='book'?'예약':'예약 취소',KEY:action+':'+random(),AT:now().toISOString()});}
 if(!['state','search','detail','reviews','count','times','reservations','past','ratingList','favorites'].includes(action))s.audit.push({ACTION:action,ID:u?u.ID:'visitor',AT:now().toISOString()});save(s);return result;}
 return {execute,state,routes};
}
return {create,routes};});
