/* New UI compatibility layer for original controller modules. No external provider calls. */
(function(){'use strict';
const D=document,esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='drher-demo:v1',store={load:()=>JSON.parse(localStorage.getItem(KEY)||'null'),save:s=>localStorage.setItem(KEY,JSON.stringify(s))};
const backend=DrHerModules.create({fixtures:DrHerFixtures,store});window.DrHerWorkspace={backend};
let view=new URLSearchParams(location.search).get('view')||D.body.dataset.initialView||'search',selected=new URLSearchParams(location.search).has('H_IDX')?{H_IDX:new URLSearchParams(location.search).get('H_IDX')}:null,message='',error='',snapshot;
const names={search:'병원 찾기',reservations:'내 예약',past:'지난 진료·후기',favorites:'관심 병원',profile:'건강수첩',points:'포인트',notice:'공지사항',faq:'자주 묻는 질문',qna:'문의하기',guide:'이용 가이드',accounts:'로그인',register:'회원가입',recover:'비밀번호 찾기',withdraw:'회원 탈퇴',admin:'운영 관리',catalog:'병원 관리'};
const input=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(name,label,value='')=>`<label>${label}<textarea name="${name}" rows="5" required>${esc(value)}</textarea></label>`;
const button=(action,label,data={})=>`<button type="button" data-action="${action}" data-values="${esc(JSON.stringify(data))}">${label}</button>`;
const link=(v,label)=>`<a href="?view=${v}" data-view="${v}">${label}</a>`;
const empty=msg=>`<p class="empty">${msg}</p>`;
const form=(action,contents,label='저장')=>`<form data-command="${action}">${contents}<button type="submit">${label}</button></form>`;
function call(action,p={}){return backend.execute(action,p);}
function records(rows,render){return rows.length?`<div class="records">${rows.map(render).join('')}</div>`:empty('등록된 항목이 없습니다. 새 항목을 등록하거나 다른 조건으로 검색해주세요.');}
const pad=n=>String(n).padStart(2,'0'),localDate=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate()),weekday=d=>'일월화수목금토'[d.getDay()];
const parseDay=v=>{const m=String(v||'').match(/(\d{4})\D(\d{2})\D(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null;};
const dateBlock=v=>{const d=parseDay(v);return d?`<div class="date-block" aria-hidden="true"><span>${d.getMonth()+1}월</span><strong>${d.getDate()}</strong><span>${weekday(d)}요일</span></div>`:'';};
const chip=(text,tone='')=>`<span class="chip ${tone}">${esc(text)}</span>`;
const rating=r=>r?`<span class="rating" aria-label="평점 ${r}점"><strong>${Number(r).toFixed(1)}</strong>/5</span>`:'<span class="rating none">평점 없음</span>';
const doctors=text=>String(text||'').split(/\s*\/\s*/).filter(Boolean).map(t=>{const [name,...rest]=t.split(/\s+—\s+/);return `<li><strong>${esc(name)}</strong>${rest.length?`<span>${esc(rest.join(' — '))}</span>`:''}</li>`;}).join('');
const hourText=h=>h.HOUR||(h.ONHOUR&&h.OFFHOUR?h.ONHOUR.slice(0,2)+':'+h.ONHOUR.slice(2)+' ~ '+h.OFFHOUR.slice(0,2)+':'+h.OFFHOUR.slice(2):'');
function days(h){const out=[];for(let i=0;i<=7;i++){const d=new Date();d.setDate(d.getDate()+i);const times=h.REG_CHK==='Y'?call('times',{H_IDX:h.H_IDX,year:String(d.getFullYear()),month:pad(d.getMonth()+1),day:pad(d.getDate())}):[];out.push({d,date:localDate(d),count:times.length});}return out;}
function nextVisit(u){if(!u)return null;try{return call('reservations')[0]||null;}catch(e){return null;}}
function render(){try{snapshot=call('state');}catch(e){D.body.innerHTML='<main><h1>저장소를 읽을 수 없습니다</h1><p>'+esc(e.message)+'</p></main>';return;}const u=snapshot.user;
D.getElementById('workspace').innerHTML=`<header class="service-header"><a href="?view=search" data-view="search" class="brand"><svg class="brand-mark" viewBox="0 0 28 28" aria-hidden="true"><rect x="1" y="1" width="26" height="26" rx="7"/><path d="M14 7.5v13M7.5 14h13"/></svg>Dr.Her <span>진료 예약</span></a><nav class="service-nav" aria-label="주 메뉴">${['search','reservations','past','favorites','profile','points','notice','faq','qna','guide'].map(k=>`<a href="?view=${k}" data-view="${k}" ${view===k?'aria-current="page"':''}>${names[k]}</a>`).join('')}${u&&u.ROLE==='admin'?link('admin','운영 관리')+link('catalog','병원 관리'):''}</nav><div class="account">${u?`<span>${esc(u.NAME)} · ${u.ROLE==='admin'?'관리자':'회원'}</span> `+button('logout','로그아웃'):link('accounts','로그인')+' '+link('register','회원가입')}</div></header><div class="environment">합성 데이터 체험 · 실제 진료 예약, 결제, 메일 전송은 발생하지 않습니다.</div><main class="work-main"><div class="page-heading"><h1>${names[view]||'병원 정보'}</h1><p>${u?'내 포인트 '+u.POINT.toLocaleString()+'점':'병원을 검색하고 로그인하여 예약을 신청하세요.'}</p></div><div role="status" class="success">${esc(message)}</div><div role="alert" class="error">${esc(error)}</div><div id="content"></div></main><footer>Dr.Her 원본 업무 기반 합성 체험 ${button('reset','체험 데이터 초기화')} ${link('withdraw','회원 탈퇴')} <a href="/hospital/main/">원본 경로 홈</a></footer>`;
try{D.getElementById('content').innerHTML=content(view,u);}catch(e){D.getElementById('content').innerHTML=empty(esc(e.message)+' '+link('accounts','로그인으로 이동'));}bind();}
function content(v,u){
 if(v==='accounts')return `<div class="two-column"><section class="form-column">${form('login',input('ID','아이디',DrHerFixtures.SESSION.ID)+input('PWD','비밀번호','','password'),'로그인')}<p class="quiet-links">${link('recover','비밀번호 찾기')} · ${link('register','회원가입')}</p></section><aside><h2>체험 계정</h2><dl class="facts"><dt>회원</dt><dd><code>demo</code> / <code>DemoPass123!</code></dd><dt>관리자</dt><dd><code>admin</code> / <code>DemoPass123!</code></dd></dl><p>회원은 예약·후기·관심 병원을, 관리자는 예약 처리·회원·후기·병원 정보를 다룹니다.</p></aside></div>`;
 if(v==='register')return `<div class="form-column">${form('register',input('ID','아이디','','text','required minlength="3"')+input('NAME','이름','','text','required')+input('EMAIL','이메일','','email','required')+input('PWD','비밀번호','','password','required minlength="10"'),'가입하기')}</div>`;
 if(v==='recover')return `<div class="two-column"><section><h2>재설정 링크 요청</h2>${form('recover',input('ID','아이디')+input('EMAIL','이메일','','email'),'로컬 메일함에 링크 생성')}<h2>새 비밀번호</h2>${form('resetPassword',input('TOKEN','재설정 토큰')+input('PWD','새 비밀번호','','password','minlength="10"'),'비밀번호 변경')}</section><section><h2>합성 로컬 메일함</h2>${records(snapshot.outbox,m=>`<article><p>${esc(m.TO)} · ${esc(m.TEXT)}</p><code>${esc(m.TOKEN)}</code></article>`)}</section></div>`;
 if(v==='search'){const q=selected&&selected.search||{};const rows=call('search',{QUERY:q.SORT==='rating'?'hplist.selectRateHpList':'hplist.selectAllHpList',SEARCH_CHK:q.SEARCHVALUE?'Y':'N',SEARCHTYPE:q.SEARCHTYPE||'HOSP',...q}).list.filter(h=>h.H_IDX);const majors=[...snapshot.catalog.filter(h=>h.DEL_CHK==='0').reduce((m,h)=>m.set(h.MAJOR,(m.get(h.MAJOR)||0)+1),new Map())];const opt=(v,l,cur)=>`<option value="${v}" ${cur===v?'selected':''}>${l}</option>`;const next=nextVisit(u);const now=new Date(),today=next?[]:rows.filter(h=>h.REG_CHK==='Y').map(h=>{const t=call('times',{H_IDX:h.H_IDX,year:String(now.getFullYear()),month:pad(now.getMonth()+1),day:pad(now.getDate())});return {h,count:t.length,first:t[0]};}).filter(x=>x.count).sort((a,b)=>a.first.localeCompare(b.first));const open=rows.filter(h=>h.REG_CHK==='Y').length;
  return `<div class="two-column search-intro"><section><form data-command="search" class="search-form"><label>검색 조건<select name="SEARCHTYPE">${opt('HOSP','병원명',q.SEARCHTYPE)}${opt('MAJOR','진료과',q.SEARCHTYPE)}${opt('ADDR','주소',q.SEARCHTYPE)}</select></label>${input('SEARCHVALUE','검색어',q.SEARCHVALUE||'','search','placeholder="예: 내과, 햇살동"')}<label>정렬<select name="SORT">${opt('default','기본 순서',q.SORT)}${opt('rating','평점순',q.SORT)}${opt('distance','수동 위치에서 가까운 순',q.SORT)}</select></label><button>병원 검색</button><details><summary>위치 직접 입력</summary>${input('LAT','위도',q.LAT||'37.5665','number','step="any" min="-90" max="90"')+input('LON','경도',q.LON||'126.978','number','step="any" min="-180" max="180"')}<p>지도를 호출하지 않고 입력한 좌표에서의 거리를 계산합니다.</p></details></form><div class="major-filter" role="group" aria-label="진료과로 바로 찾기">${majors.map(([m,n])=>`<button type="button" class="filter-chip" data-action="search" data-values="${esc(JSON.stringify({SEARCHTYPE:'MAJOR',SEARCHVALUE:m,SORT:q.SORT||'default'}))}" aria-pressed="${q.SEARCHTYPE==='MAJOR'&&q.SEARCHVALUE===m}">${esc(m)} <span>${n}</span></button>`).join('')}</div></section><aside class="next-visit">${next?`<h2>다음 예약</h2><div class="visit">${dateBlock(next.RESERV1)}<div><strong>${esc(next.HOSP)}</strong><p>${esc(next.CURED||'')} · ${esc(next.RESERV2)}</p></div></div>${link('reservations','내 예약 전체 보기')}`:`<h2>오늘 예약 가능</h2>${today.length?`<ul class="today-list">${today.slice(0,4).map(t=>`<li><button type="button" class="today-slot" data-action="slots" data-values="${esc(JSON.stringify({H_IDX:String(t.h.H_IDX),DATE:localDate(new Date())}))}"><strong>${esc(t.h.HOSP)}</strong><span>${esc(t.h.MAJOR)} · ${t.first}부터 ${t.count}개</span></button></li>`).join('')}</ul>`:'<p>오늘 남은 예약 시간이 없습니다. 병원 상세에서 7일 안의 날짜를 확인하세요.</p>'}${u?link('reservations','내 예약 확인'):link('accounts','로그인하고 예약하기')}`}</aside></div><div class="result-heading"><h2>검색 결과 ${rows.length}곳</h2><p>${q.SEARCHVALUE?esc(q.SEARCHVALUE)+' 검색 · ':''}온라인 예약 가능 ${open}곳</p></div>${records(rows,h=>`<article class="result-row hospital-row"><div><div class="row-title"><h3>${esc(h.HOSP)}</h3>${chip(h.MAJOR,'major')}${h.REG_CHK==='Y'?chip('온라인 예약','open'):chip('전화 문의','closed')}</div><p class="summary">${esc(String(h.H_COMM||'').split(/(?<=다\.)\s/)[0])}</p><p class="meta">${esc(hourText(h))} · ${h.INTERVALL?esc(h.INTERVALL)+'분 간격 · ':''}${esc(h.ADDR)}${h.DISTANCE?' · 약 '+(h.DISTANCE/1000).toFixed(1)+'km':''}</p></div><div class="row-side">${rating(h.RATE)}${button('detail',h.REG_CHK==='Y'?'상세·예약':'병원 정보',{H_IDX:h.H_IDX})}</div></article>`)}`;}
 if(v==='detail'){const h=call('detail',selected);if(!h)return empty('병원 정보를 찾을 수 없습니다.');const rv=call('hospitalReviews',{H_IDX:h.H_IDX}),strip=days(h);return `<div class="two-column detail-layout"><section><div class="detail-heading"><div class="row-title"><h2>${esc(h.HOSP)}</h2>${chip(h.MAJOR,'major')}</div><p class="lede">${esc(h.H_COMM||'')}</p></div><dl class="facts"><dt>진료 시간</dt><dd>${esc(h.HOUR)}${h.MEAL_TIME?' · 점심 '+esc(h.MEAL_TIME.slice(0,2))+'시대 제외':''}</dd><dt>예약 간격</dt><dd>${esc(h.INTERVALL)}분</dd><dt>주소</dt><dd>${esc(h.ADDR)}</dd><dt>연락처</dt><dd>${esc(h.TEL)}</dd></dl>${h.DOC_COMM?`<h3>의료진 소개</h3><ul class="doctors">${doctors(h.DOC_COMM)}</ul>`:''}<h3>진료 후기 ${rv.count}건</h3>${rv.count?`<div class="score-grid">${Object.entries(rv.scores).map(([k,v])=>`<div><span>${k}</span><meter min="1" max="5" value="${v}" aria-label="${k} ${v}점"></meter><strong>${v}</strong></div>`).join('')}</div><ul class="reviews">${rv.list.map(r=>`<li><span>${esc(r.REG)} · ${r.RATE.toFixed(2)}점</span><p>${esc(r.COMM)}</p></li>`).join('')}</ul>`:empty('아직 등록된 후기가 없습니다.')}<p>${button('favorite','관심 병원 등록',{H_IDX:h.H_IDX})}</p></section><aside class="booking-panel"><h2>진료 예약 신청</h2>${h.REG_CHK==='Y'?`<p>오늘부터 7일 안에서 날짜를 고르세요. 숫자는 지금 남은 예약 시간입니다.</p><div class="day-strip" role="group" aria-label="예약 날짜">${strip.map(x=>`<button type="button" class="day" data-action="slots" data-values="${esc(JSON.stringify({H_IDX:String(h.H_IDX),DATE:x.date}))}" ${x.count?'':'disabled'} aria-label="${x.d.getMonth()+1}월 ${x.d.getDate()}일 ${weekday(x.d)}요일 ${x.count?'예약 가능 '+x.count+'개':'예약 가능 시간 없음'}"><span>${weekday(x.d)}</span><strong>${x.d.getDate()}</strong><small>${x.count?x.count+'개':'마감'}</small></button>`).join('')}</div><details><summary>날짜 직접 입력</summary>${form('slots',`<input type="hidden" name="H_IDX" value="${h.H_IDX}">${input('DATE','희망 날짜',new Date(Date.now()+86400000).toISOString().slice(0,10),'date','required')}`,'예약 시간 보기')}</details><p class="note">예약 확정 시 합성 포인트 100점을 사용하고, 진료 30분 전까지 취소하면 돌려받습니다.</p>`:empty('현재 온라인 예약을 받지 않는 병원입니다. '+esc(h.TEL)+'로 문의해주세요.')}</aside></div>`;}
 if(v==='booking'){const h=call('detail',selected);const [year,month,day]=selected.DATE.split('-'),times=call('times',{H_IDX:h.H_IDX,year,month,day}),d=parseDay(selected.DATE);const groups=[['오전',times.filter(t=>+t.slice(0,2)<12)],['오후',times.filter(t=>+t.slice(0,2)>=12)]].filter(g=>g[1].length);return `<div class="two-column"><section><h2>${d?d.getMonth()+1+'월 '+d.getDate()+'일 '+weekday(d)+'요일':esc(selected.DATE)} 예약 시간</h2>${times.length?form('book',`<input type="hidden" name="H_IDX" value="${h.H_IDX}"><input type="hidden" name="CURED" value="${esc(h.MAJOR)}"><input type="hidden" name="YEAR" value="${year}"><input type="hidden" name="MONTH" value="${month}"><input type="hidden" name="DAY" value="${day}"><input type="hidden" name="KEY" value="${Date.now()}"><fieldset class="slots"><legend>남은 시간 ${times.length}개 · ${esc(h.INTERVALL)}분 간격</legend>${groups.map(([g,list])=>`<div class="slot-group"><h3>${g}</h3><div class="slot-grid">${list.map(t=>`<label class="slot"><input type="radio" name="RESERV2" value="${t}" required><span>${t}</span></label>`).join('')}</div></div>`).join('')}</fieldset>${u?'':`<p class="note">예약 확정은 로그인 후 가능합니다. ${link('accounts','로그인')}</p>`}`,'100점으로 예약 확정'):empty('예약 가능한 시간이 없습니다. 날짜를 다시 선택해주세요.')}</section><aside class="reservation-summary"><h2>신청 내용</h2><dl class="facts"><dt>병원</dt><dd>${esc(h.HOSP)}</dd><dt>진료과</dt><dd>${esc(h.MAJOR)}</dd><dt>날짜</dt><dd>${esc(selected.DATE)}</dd><dt>시간</dt><dd data-summary-time>시간을 선택해주세요</dd><dt>포인트</dt><dd>100점 사용${u?' · 보유 '+u.POINT.toLocaleString()+'점':''}</dd></dl>${button('detail','날짜 다시 선택',{H_IDX:h.H_IDX})}</aside></div>`;}
 if(v==='reservations'||v==='past'){const rows=call(v==='past'?'ratingList':'reservations');return records(rows,r=>`<article class="result-row visit-row">${dateBlock(r.RESERV1)}<div class="visit-body"><h2>${esc(r.HOSP)}</h2><p>${esc(r.CURED||'')}${r.CURED?' · ':''}${esc(r.RESERV1)} ${esc(r.RESERV2||'')}</p>${chip(v==='past'?(r.REG?'후기 작성 완료':'진료 완료 · 후기 대기'):(r.STATE&&r.STATE!=='미완료'?r.STATE:'예약 확정'),v==='past'?(r.REG?'done':'pending'):'open')}</div><div class="row-side">${v==='past'?r.REG?'':button('reviewForm','후기 작성',r):button('cancel','예약 취소',{H_IDX:r.H_IDX})}</div></article>`);}
 if(v==='review')return form('rate',`<input type="hidden" name="NUM" value="${selected.NUM}"><input type="hidden" name="H_IDX" value="${selected.H_IDX}"><input type="hidden" name="RESERV1" value="${esc(selected.RESERV1)}">${['친절','설명','시설','만족도'].map((label,i)=>`<label>${label}<select name="RATE${i+1}">${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label>`).join('')}${area('COMM','진료 후기')}`,'후기 등록');
 if(v==='favorites')return records(call('favorites'),h=>`<article class="result-row"><div><h2>${esc(h.HOSP)}</h2><p>${esc(h.ADDR)}</p></div><div>${button('detail','상세·예약',{H_IDX:h.H_IDX})}${button('unfavorite','관심 해제',{H_IDX:h.H_IDX})}</div></article>`);
 if(v==='profile'){if(!u)throw Error('로그인이 필요합니다.');return `<div class="two-column"><section>${form('profile',['NAME','PHONE','ADDR','HEIGHT','WEIGHT','B_TYPE'].map((k,i)=>input(k,['이름','전화번호','주소','키(cm)','몸무게(kg)','혈액형'][i],u[k]||'')).join(''))}</section><aside><h2>프로필 사진</h2>${u.AVATAR?`<img class="avatar" src="${esc(u.AVATAR)}" alt="내 프로필 사진">`:empty('등록한 사진이 없습니다.')}<label>PNG·JPEG 사진 (200KB 이하)<input type="file" id="avatar" accept="image/png,image/jpeg"></label>${button('avatar','사진 삭제',{DATA:''})}<p>건강수첩은 합성 정보 체험용입니다. 실제 건강정보를 입력하지 마세요.</p></aside></div>`;}
 if(v==='points'){if(!u)throw Error('로그인이 필요합니다.');return `<div class="two-column"><section><h2>합성 포인트 충전</h2><p>현재 ${u.POINT}점 · 실제 결제는 발생하지 않습니다.</p>${form('charge',input('POINT','충전할 포인트',1000,'number','min="100" max="10000" required')+`<input name="KEY" type="hidden" value="${Date.now()}">`,'합성 충전')}</section><section><h2>포인트 내역</h2>${records(snapshot.ledger,l=>`<article><strong>${l.AMOUNT>0?'+':''}${l.AMOUNT}점</strong> ${esc(l.REASON)}</article>`)}</section></div>`;}
 if(v==='withdraw')return `<div class="form-column"><p>예정 예약을 모두 취소한 뒤 현재 비밀번호로 확인합니다. 탈퇴하면 로그아웃되며 이 계정으로 로그인할 수 없습니다.</p>${form('withdraw',input('PWD','현재 비밀번호','','password','required'),'회원 탈퇴')}</div>`;
 if(['notice','faq','qna'].includes(v)){if(v==='qna'&&!u)throw Error('로그인이 필요합니다.');const may=u&&(v==='qna'||u.ROLE==='admin');const query=selected&&selected.FILTER||'';return `${form('boardSearch',input('FILTER','제목·내용 검색',query),'검색')}${may?`<details><summary>${names[v]} 등록</summary>${boardForm(v)}</details>`:''}${records(snapshot[v].filter(r=>(r.TITLE+' '+r.CONTENTS).toLowerCase().includes(query.toLowerCase())),r=>`<article><h2>${esc(r.TITLE)}</h2><p class="preserve">${esc(r.CONTENTS)}</p>${(r.files||[]).map(f=>`<a download="${esc(f.NAME)}" href="data:text/plain;charset=utf-8,${encodeURIComponent(f.TEXT)}">${esc(f.NAME)} 내려받기</a>`).join('')}${r.ANSWER?`<section class="answer"><h3>관리자 답변</h3><p>${esc(r.ANSWER)}</p></section>`:''}${may?`<details><summary>수정</summary>${boardForm(v,r)}</details>${button(v+'.delete','삭제',{IDX:r.IDX})}`:''}${v==='qna'&&u.ROLE==='admin'?form('qna.answer',`<input type="hidden" name="IDX" value="${r.IDX}">${area('ANSWER','답변',r.ANSWER||'')}`,'답변 저장')+button('qna.answer','답변 삭제',{IDX:r.IDX,ANSWER:''}):''}</article>`)}`;}
 if(v==='catalog'){if(!snapshot.admin)throw Error('관리자 권한이 필요합니다.');return `<details><summary>병원 등록</summary>${catalogForm()}</details>${records(snapshot.catalog.filter(h=>h.DEL_CHK==='0'),h=>`<article><h2>${esc(h.HOSP)}</h2><p>${esc(h.ADDR)} · ${esc(h.MAJOR)}</p><details><summary>병원 정보 수정</summary>${catalogForm(h)}</details>${button('catalog.delete','병원 삭제',{H_IDX:h.H_IDX})}</article>`)}`;}
 if(v==='admin'){if(!snapshot.admin)throw Error('관리자 권한이 필요합니다.');const a=snapshot.admin;const filter=selected&&selected.FILTER||'';const matches=r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase());const hosp=id=>(snapshot.catalog.find(h=>String(h.H_IDX)===String(id))||{}).HOSP||'병원 '+id;const status={B:['예정','open'],A:['진료 완료','done'],C:['취소','closed']};const count=k=>a.reservations.filter(r=>r.DEL_CHK===k).length;const stopped=a.members.filter(m=>!m.ACTIVE).length;return `<dl class="admin-counts"><div><dt>처리할 예정 예약</dt><dd>${count('B')}건</dd></div><div><dt>진료 완료</dt><dd>${count('A')}건</dd></div><div><dt>취소</dt><dd>${count('C')}건</dd></div><div><dt>회원</dt><dd>${a.members.filter(m=>m.ROLE!=='admin').length}명${stopped?`<small>이용 중지 ${stopped}명</small>`:''}</dd></div><div><dt>후기</dt><dd>${a.ratings.length}건</dd></div></dl>${form('boardSearch',input('FILTER','회원·예약·후기 검색',filter),'검색')}<nav class="section-nav" aria-label="운영 메뉴">${['notice','faq','qna','catalog'].map(k=>link(k,names[k]+' 관리')).join('')}</nav><h2>예약 관리</h2>${records(a.reservations.filter(matches).slice().sort((x,y)=>(x.DEL_CHK==='B'?0:1)-(y.DEL_CHK==='B'?0:1)),r=>`<article class="result-row visit-row">${dateBlock(r.RESERV1)}<div class="visit-body"><h3>${esc(hosp(r.H_IDX))}</h3><p>${esc(r.ID)} · ${esc(r.CURED||'')} · ${esc(r.RESERV1)} ${esc(r.RESERV2)}</p>${chip((status[r.DEL_CHK]||[r.DEL_CHK])[0],(status[r.DEL_CHK]||[])[1]||'')}</div>${r.DEL_CHK==='B'?`<div class="row-side">${button('admin.reservation','진료 완료',{NUM:r.NUM,STATUS:'A'})}${button('admin.reservation','예약 취소·환급',{NUM:r.NUM,STATUS:'C'})}</div>`:''}</article>`)}<h2>회원 관리</h2>${records(a.members.filter(matches),m=>`<article class="result-row"><div><h3>${esc(m.NAME)} <span class="muted">${esc(m.ID)}</span></h3>${chip(m.ROLE==='admin'?'관리자':m.ACTIVE?'이용 가능':'이용 중지',m.ACTIVE?'open':'closed')}</div>${m.ROLE!=='admin'?button('admin.member',m.ACTIVE?'이용 중지':'이용 재개',{ID:m.ID,ACTIVE:!m.ACTIVE}):''}</article>`)}<h2>후기 관리</h2>${records(a.ratings.filter(matches),r=>`<article><p><strong>${esc(hosp(r.H_IDX))}</strong> · ${esc(r.ID)} · ${esc(r.REG||'')}</p><details><summary>후기 수정·삭제</summary>${form('admin.review',`<input type="hidden" name="NUM" value="${r.NUM}">${area('COMM','후기 내용',r.COMM)}`,'후기 수정')}${button('admin.review','후기 삭제',{NUM:r.NUM,DELETE:true})}</details><p class="preserve">${esc(r.COMM)}</p></article>`)}<h2>최근 변경 기록</h2>${records(a.audit.slice(-15).reverse(),r=>`<article class="audit">${esc(r.AT)} · ${esc(r.ID)} · ${esc(r.ACTION)}</article>`)}`;}
 if(v==='guide')return `<div class="guide"><section><h2>병원 찾기</h2><p>병원명, 주소, 진료과를 검색한 뒤 상세에서 진료 시간과 예약 여부를 확인합니다. 수동 좌표를 입력하면 거리순으로 비교할 수 있습니다.</p>${link('search','병원 찾기 시작')}</section><section><h2>진료 예약</h2><p>로그인 후 병원 상세에서 날짜와 시간을 선택합니다. 신청 내용을 확인하고 확정하면 내 예약에 표시됩니다. 진료 30분 전까지 취소하면 포인트가 반환됩니다.</p>${link('reservations','내 예약 확인')}</section><section><h2>지난 진료와 후기</h2><p>완료된 본인의 진료만 평가할 수 있습니다. 네 가지 점수와 후기를 작성하면 병원 평점과 최근 후기에 반영됩니다.</p>${link('past','지난 진료 보기')}</section></div>`;
 return empty('메뉴에서 이용할 업무를 선택해주세요.');}
function boardForm(kind,r={}){return form(kind+'.save',`<input type="hidden" name="IDX" value="${r.IDX||''}">${input('TITLE','제목',r.TITLE||'','text','required')}${area('CONTENTS','내용',r.CONTENTS||'')}${kind==='notice'?input('FILE_NAME','첨부 파일명 (.txt)')+'<label>첨부 텍스트<textarea name="FILE_TEXT"></textarea></label>':''}`);}
function catalogForm(h={}){return form('catalog.save',`<input type="hidden" name="H_IDX" value="${h.H_IDX||''}">${['HOSP','MAJOR','ADDR','TEL','ONHOUR','OFFHOUR','ADDR_GPS'].map((k,i)=>input(k,['병원명','진료과','주소','전화번호','시작 시간 (0900)','종료 시간 (1800)','좌표 (위도,경도)'][i],h[k]||'')).join('')}<label>예약 접수<select name="REG_CHK"><option value="Y">가능</option><option value="N" ${h.REG_CHK==='N'?'selected':''}>중지</option></select></label>`);}
// View-only transitions never touch stored state, so they must not wait on the cross-tab write lock.
// State-changing actions keep the lock; if it cannot be acquired the failure is shown, not skipped.
const VIEW_ONLY=['boardSearch','detail','slots','search','reviewForm'],LOCK_WAIT=4000;
function act(action,p){if(VIEW_ONLY.includes(action)||!navigator.locks)return executeAct(action,p);const ctrl=typeof AbortController==='function'?new AbortController():null,timer=ctrl&&setTimeout(()=>ctrl.abort(),LOCK_WAIT);return navigator.locks.request('drher-state',ctrl?{signal:ctrl.signal}:{},()=>{clearTimeout(timer);return executeAct(action,p);}).catch(e=>{clearTimeout(timer);message='';error=e&&e.name==='AbortError'?'다른 창에서 변경 사항을 저장하는 중이라 요청을 처리하지 못했습니다. 잠시 후 다시 시도해주세요.':'요청을 처리하지 못했습니다: '+(e&&e.message||e);render();});}
function executeAct(action,p){error='';message='';try{if(action==='boardSearch'){selected={FILTER:p.FILTER};}else if(action==='detail'){selected=p;view='detail';}else if(action==='slots'){selected=p;view='booking';}else if(action==='search'){selected={search:p};view='search';}else if(action==='reviewForm'){selected=p;view='review';}else{const r=call(action,p);if(action==='book'&&r.code!==0)throw Error(r.message||'포인트 또는 중복 예약을 확인해주세요.');message=r&&r.message||'변경사항을 저장했습니다.';if(action==='login'||action==='logout'||action==='withdraw')view='search';if(action==='book'||action==='cancel')view='reservations';if(action==='rate')view='past';if(action==='register'||action==='resetPassword')view='accounts';if(action==='reset')view='search';}}catch(e){error=e.message;}render();}
function bind(){D.querySelectorAll('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();view=a.dataset.view;selected=null;error='';message='';history.replaceState(null,'','?view='+view);render();});D.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action,JSON.parse(b.dataset.values)));D.querySelectorAll('[data-command]').forEach(f=>f.onsubmit=e=>{e.preventDefault();act(f.dataset.command,Object.fromEntries(new FormData(f)));});D.querySelectorAll('input[name=RESERV2]').forEach(r=>r.onchange=()=>{const t=D.querySelector('[data-summary-time]');if(t)t.textContent=r.value;});const f=D.getElementById('avatar');if(f)f.onchange=()=>{const file=f.files[0];if(!file)return;if(file.size>200000||!['image/png','image/jpeg'].includes(file.type)){error='200KB 이하 PNG 또는 JPEG 파일을 선택해주세요.';render();return;}const reader=new FileReader();reader.onload=()=>act('avatar',{DATA:reader.result});reader.readAsDataURL(file);};}
render();})();
