/* New UI compatibility layer for original controller modules. No external provider calls. */
(function(){'use strict';
const D=document,esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='drher-demo:v1',store={load:()=>JSON.parse(localStorage.getItem(KEY)||'null'),save:s=>localStorage.setItem(KEY,JSON.stringify(s))};
const backend=DrHerModules.create({fixtures:DrHerFixtures,store});window.DrHerWorkspace={backend};
let view=new URLSearchParams(location.search).get('view')||D.body.dataset.initialView||'search',selected=new URLSearchParams(location.search).has('H_IDX')?{H_IDX:new URLSearchParams(location.search).get('H_IDX')}:null,message='',error='',snapshot;
const names={search:'병원 찾기',reservations:'내 예약',past:'지난 진료·후기',favorites:'관심 병원',profile:'건강수첩',points:'포인트',notice:'공지사항',faq:'자주 묻는 질문',qna:'문의하기',guide:'이용 가이드',accounts:'로그인',register:'회원가입',recover:'비밀번호 찾기',withdraw:'회원 탈퇴',admin:'운영 관리',catalog:'병원 관리'};
const input=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(name,label,value='')=>`<label>${label}<textarea name="${name}" rows="5" required>${esc(value)}</textarea></label>`;
const button=(action,label,data={})=>`<button type="button" data-action="${action}" data-values="${esc(JSON.stringify(data))}">${label}</button>`;
const link=(v,label)=>`<a href="?view=${v}" data-view="${v}">${label}</a>`;
const empty=msg=>`<p class="empty">${msg}</p>`;
const form=(action,contents,label='저장')=>`<form data-command="${action}">${contents}<button type="submit">${label}</button></form>`;
function call(action,p={}){return backend.execute(action,p);}
function records(rows,render){return rows.length?`<div class="records">${rows.map(render).join('')}</div>`:empty('등록된 항목이 없습니다. 새 항목을 등록하거나 다른 조건으로 검색해주세요.');}
function render(){try{snapshot=call('state');}catch(e){D.body.innerHTML='<main><h1>저장소를 읽을 수 없습니다</h1><p>'+esc(e.message)+'</p></main>';return;}const u=snapshot.user;
D.getElementById('workspace').innerHTML=`<header class="service-header"><a href="?view=search" data-view="search" class="brand">Dr.Her <span>진료 예약</span></a><div>${u?esc(u.NAME)+' · '+(u.ROLE==='admin'?'관리자':'회원')+' '+button('logout','로그아웃'):link('accounts','로그인')+' '+link('register','회원가입')}</div></header><div class="environment">합성 데이터 체험 · 실제 진료 예약, 결제, 메일 전송은 발생하지 않습니다.</div><nav class="service-nav" aria-label="주 메뉴">${['search','reservations','past','favorites','profile','points','notice','faq','qna','guide'].map(k=>`<a href="?view=${k}" data-view="${k}" ${view===k?'aria-current="page"':''}>${names[k]}</a>`).join('')}${u&&u.ROLE==='admin'?link('admin','운영 관리')+link('catalog','병원 관리'):''}</nav><main class="work-main"><div class="page-heading"><h1>${names[view]||'병원 정보'}</h1><p>${u?'내 포인트 '+u.POINT.toLocaleString()+'점':'병원을 검색하고 로그인하여 예약을 신청하세요.'}</p></div><div role="status" class="success">${esc(message)}</div><div role="alert" class="error">${esc(error)}</div><div id="content"></div></main><footer>Dr.Her 원본 업무 기반 합성 체험 ${button('reset','체험 데이터 초기화')} ${link('withdraw','회원 탈퇴')} <a href="/hospital/main/">원본 경로 홈</a></footer>`;
try{D.getElementById('content').innerHTML=content(view,u);}catch(e){D.getElementById('content').innerHTML=empty(esc(e.message)+' '+link('accounts','로그인으로 이동'));}bind();}
function content(v,u){
 if(v==='accounts')return `<div class="form-column"><p>합성 계정: demo / DemoPass123! · 관리자: admin / DemoPass123!</p>`+form('login',input('ID','아이디',DrHerFixtures.SESSION.ID)+input('PWD','비밀번호','','password'),'로그인')+link('recover','비밀번호 찾기')+'</div>';
 if(v==='register')return `<div class="form-column">${form('register',input('ID','아이디','','text','required minlength="3"')+input('NAME','이름','','text','required')+input('EMAIL','이메일','','email','required')+input('PWD','비밀번호','','password','required minlength="10"'),'가입하기')}</div>`;
 if(v==='recover')return `<div class="two-column"><section><h2>재설정 링크 요청</h2>${form('recover',input('ID','아이디')+input('EMAIL','이메일','','email'),'로컬 메일함에 링크 생성')}<h2>새 비밀번호</h2>${form('resetPassword',input('TOKEN','재설정 토큰')+input('PWD','새 비밀번호','','password','minlength="10"'),'비밀번호 변경')}</section><section><h2>합성 로컬 메일함</h2>${records(snapshot.outbox,m=>`<article><p>${esc(m.TO)} · ${esc(m.TEXT)}</p><code>${esc(m.TOKEN)}</code></article>`)}</section></div>`;
 if(v==='search'){const q=selected&&selected.search||{};const rows=call('search',{QUERY:q.SORT==='rating'?'hplist.selectRateHpList':'hplist.selectAllHpList',SEARCH_CHK:q.SEARCHVALUE?'Y':'N',SEARCHTYPE:q.SEARCHTYPE||'HOSP',...q}).list.filter(h=>h.H_IDX);return `<div class="two-column search-intro"><section><h2>가까운 진료를 찾아보세요</h2><form data-command="search"><label>검색 조건<select name="SEARCHTYPE"><option value="HOSP">병원명</option><option value="MAJOR">진료과</option><option value="ADDR">주소</option></select></label>${input('SEARCHVALUE','검색어',q.SEARCHVALUE||'')}<label>정렬<select name="SORT"><option value="default">기본 순서</option><option value="rating">평점순</option><option value="distance">수동 위치에서 가까운 순</option></select></label><details><summary>위치 직접 입력</summary>${input('LAT','위도',q.LAT||'37.5665','number','step="any" min="-90" max="90"')+input('LON','경도',q.LON||'126.978','number','step="any" min="-180" max="180"')}<p>지도를 호출하지 않고 입력한 좌표에서의 거리를 계산합니다.</p></details><button>병원 검색</button></form></section><aside><h2>예약 안내</h2><p>진료과와 예약 시간을 선택하면 신청 내용을 확인할 수 있습니다. 한 병원에 한 건의 예정 예약을 유지합니다.</p>${link('reservations','내 예약 확인')}</aside></div><h2>검색 결과 ${rows.length}곳</h2>${records(rows,h=>`<article class="result-row"><div><h3>${esc(h.HOSP)}</h3><p>${esc(h.MAJOR)} · ${esc(h.ADDR)}</p><p>${esc(h.HOUR)} · ${esc(h.TEL)}${h.DISTANCE?' · '+h.DISTANCE+'m':''}</p></div><div><p>평점 ${h.RATE||'아직 없음'}</p>${button('detail','상세·예약',{H_IDX:h.H_IDX})}</div></article>`)}`;}
 if(v==='detail'){const h=call('detail',selected);if(!h)return empty('병원 정보를 찾을 수 없습니다.');return `<div class="two-column"><section><h2>${esc(h.HOSP)}</h2><dl><dt>진료과</dt><dd>${esc(h.MAJOR)}</dd><dt>주소</dt><dd>${esc(h.ADDR)}</dd><dt>연락처</dt><dd>${esc(h.TEL)}</dd><dt>진료 시간</dt><dd>${esc(h.HOUR)}</dd><dt>평점</dt><dd>${h.RATE||'아직 없음'}</dd></dl>${button('favorite','관심 병원 등록',{H_IDX:h.H_IDX})}</section><aside><h2>진료 예약 신청</h2>${h.REG_CHK==='Y'?form('slots',`<input type="hidden" name="H_IDX" value="${h.H_IDX}">${input('DATE','희망 날짜',new Date(Date.now()+86400000).toISOString().slice(0,10),'date','required')}`,'예약 시간 보기'):empty('현재 온라인 예약을 받지 않는 병원입니다.')}</aside></div>`;}
 if(v==='booking'){const h=call('detail',selected);const [year,month,day]=selected.DATE.split('-'),times=call('times',{H_IDX:h.H_IDX,year,month,day});return `<div class="two-column"><section><h2>예약 시간 선택</h2>${times.length?form('book',`<input type="hidden" name="H_IDX" value="${h.H_IDX}"><input type="hidden" name="CURED" value="${esc(h.MAJOR)}"><input type="hidden" name="YEAR" value="${year}"><input type="hidden" name="MONTH" value="${month}"><input type="hidden" name="DAY" value="${day}"><input type="hidden" name="KEY" value="${Date.now()}"><label>시간<select name="RESERV2">${times.map(t=>`<option>${t}</option>`).join('')}</select></label>`,'100점으로 예약 확정'):empty('예약 가능한 시간이 없습니다. 날짜를 다시 선택해주세요.')}</section><aside class="reservation-summary"><h2>신청 내용</h2><p>${esc(h.HOSP)}</p><p>${esc(h.MAJOR)}</p><p>${esc(selected.DATE)}</p><p>확정 시 합성 포인트 100점 사용</p>${button('detail','날짜 다시 선택',{H_IDX:h.H_IDX})}</aside></div>`;}
 if(v==='reservations'||v==='past'){const rows=call(v==='past'?'ratingList':'reservations');return records(rows,r=>`<article class="result-row"><div><h2>${esc(r.HOSP)}</h2><p>${esc(r.RESERV1)} ${esc(r.RESERV2||'')} · ${esc(r.STATE||'예약 확정')}</p></div>${v==='past'?r.REG?'<p>후기 작성 완료</p>':button('reviewForm','후기 작성',r):button('cancel','예약 취소',{H_IDX:r.H_IDX})}</article>`);}
 if(v==='review')return form('rate',`<input type="hidden" name="NUM" value="${selected.NUM}"><input type="hidden" name="H_IDX" value="${selected.H_IDX}"><input type="hidden" name="RESERV1" value="${esc(selected.RESERV1)}">${['친절','설명','시설','만족도'].map((label,i)=>`<label>${label}<select name="RATE${i+1}">${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label>`).join('')}${area('COMM','진료 후기')}`,'후기 등록');
 if(v==='favorites')return records(call('favorites'),h=>`<article class="result-row"><div><h2>${esc(h.HOSP)}</h2><p>${esc(h.ADDR)}</p></div><div>${button('detail','상세·예약',{H_IDX:h.H_IDX})}${button('unfavorite','관심 해제',{H_IDX:h.H_IDX})}</div></article>`);
 if(v==='profile'){if(!u)throw Error('로그인이 필요합니다.');return `<div class="two-column"><section>${form('profile',['NAME','PHONE','ADDR','HEIGHT','WEIGHT','B_TYPE'].map((k,i)=>input(k,['이름','전화번호','주소','키(cm)','몸무게(kg)','혈액형'][i],u[k]||'')).join(''))}</section><aside><h2>프로필 사진</h2>${u.AVATAR?`<img class="avatar" src="${esc(u.AVATAR)}" alt="내 프로필 사진">`:empty('등록한 사진이 없습니다.')}<label>PNG·JPEG 사진 (200KB 이하)<input type="file" id="avatar" accept="image/png,image/jpeg"></label>${button('avatar','사진 삭제',{DATA:''})}<p>건강수첩은 합성 정보 체험용입니다. 실제 건강정보를 입력하지 마세요.</p></aside></div>`;}
 if(v==='points'){if(!u)throw Error('로그인이 필요합니다.');return `<div class="two-column"><section><h2>합성 포인트 충전</h2><p>현재 ${u.POINT}점 · 실제 결제는 발생하지 않습니다.</p>${form('charge',input('POINT','충전할 포인트',1000,'number','min="100" max="10000" required')+`<input name="KEY" type="hidden" value="${Date.now()}">`,'합성 충전')}</section><section><h2>포인트 내역</h2>${records(snapshot.ledger,l=>`<article><strong>${l.AMOUNT>0?'+':''}${l.AMOUNT}점</strong> ${esc(l.REASON)}</article>`)}</section></div>`;}
 if(v==='withdraw')return `<div class="form-column"><p>예정 예약을 모두 취소한 뒤 현재 비밀번호로 확인합니다. 탈퇴하면 로그아웃되며 이 계정으로 로그인할 수 없습니다.</p>${form('withdraw',input('PWD','현재 비밀번호','','password','required'),'회원 탈퇴')}</div>`;
 if(['notice','faq','qna'].includes(v)){if(v==='qna'&&!u)throw Error('로그인이 필요합니다.');const may=u&&(v==='qna'||u.ROLE==='admin');const query=selected&&selected.FILTER||'';return `${form('boardSearch',input('FILTER','제목·내용 검색',query),'검색')}${may?`<details><summary>${names[v]} 등록</summary>${boardForm(v)}</details>`:''}${records(snapshot[v].filter(r=>(r.TITLE+' '+r.CONTENTS).toLowerCase().includes(query.toLowerCase())),r=>`<article><h2>${esc(r.TITLE)}</h2><p class="preserve">${esc(r.CONTENTS)}</p>${(r.files||[]).map(f=>`<a download="${esc(f.NAME)}" href="data:text/plain;charset=utf-8,${encodeURIComponent(f.TEXT)}">${esc(f.NAME)} 내려받기</a>`).join('')}${r.ANSWER?`<section class="answer"><h3>관리자 답변</h3><p>${esc(r.ANSWER)}</p></section>`:''}${may?`<details><summary>수정</summary>${boardForm(v,r)}</details>${button(v+'.delete','삭제',{IDX:r.IDX})}`:''}${v==='qna'&&u.ROLE==='admin'?form('qna.answer',`<input type="hidden" name="IDX" value="${r.IDX}">${area('ANSWER','답변',r.ANSWER||'')}`,'답변 저장')+button('qna.answer','답변 삭제',{IDX:r.IDX,ANSWER:''}):''}</article>`)}`;}
 if(v==='catalog'){if(!snapshot.admin)throw Error('관리자 권한이 필요합니다.');return `<details><summary>병원 등록</summary>${catalogForm()}</details>${records(snapshot.catalog.filter(h=>h.DEL_CHK==='0'),h=>`<article><h2>${esc(h.HOSP)}</h2><p>${esc(h.ADDR)} · ${esc(h.MAJOR)}</p><details><summary>병원 정보 수정</summary>${catalogForm(h)}</details>${button('catalog.delete','병원 삭제',{H_IDX:h.H_IDX})}</article>`)}`;}
 if(v==='admin'){if(!snapshot.admin)throw Error('관리자 권한이 필요합니다.');const a=snapshot.admin;const filter=selected&&selected.FILTER||'';const matches=r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase());return `${form('boardSearch',input('FILTER','회원·예약·후기 검색',filter),'검색')}<nav class="section-nav">${['notice','faq','qna','catalog'].map(k=>link(k,names[k]+' 관리')).join('')}</nav><h2>예약 관리</h2>${records(a.reservations.filter(matches),r=>`<article class="result-row"><p>${esc(r.ID)} · ${esc(r.RESERV1)} ${esc(r.RESERV2)} · 상태 ${esc(r.DEL_CHK)}</p>${r.DEL_CHK==='B'?`<div>${button('admin.reservation','진료 완료',{NUM:r.NUM,STATUS:'A'})}${button('admin.reservation','예약 취소·환급',{NUM:r.NUM,STATUS:'C'})}</div>`:''}</article>`)}<h2>회원 관리</h2>${records(a.members.filter(matches),m=>`<article class="result-row"><p>${esc(m.NAME)} (${esc(m.ID)}) · ${m.ACTIVE?'이용 가능':'이용 중지'}</p>${m.ROLE!=='admin'?button('admin.member',m.ACTIVE?'이용 중지':'이용 재개',{ID:m.ID,ACTIVE:!m.ACTIVE}):'관리자'}</article>`)}<h2>후기 관리</h2>${records(a.ratings.filter(matches),r=>`<article><p>${esc(r.ID)} · ${esc(r.COMM)}</p>${true?form('admin.review',`<input type="hidden" name="NUM" value="${r.NUM}">${area('COMM','후기 내용',r.COMM)}`,'후기 수정')+button('admin.review','후기 삭제',{NUM:r.NUM,DELETE:true}):''}</article>`)}<h2>최근 변경 기록</h2>${records(a.audit.slice(-15).reverse(),r=>`<article>${esc(r.AT)} · ${esc(r.ID)} · ${esc(r.ACTION)}</article>`)}`;}
 if(v==='guide')return `<div class="guide"><section><h2>병원 찾기</h2><p>병원명, 주소, 진료과를 검색한 뒤 상세에서 진료 시간과 예약 여부를 확인합니다. 수동 좌표를 입력하면 거리순으로 비교할 수 있습니다.</p>${link('search','병원 찾기 시작')}</section><section><h2>진료 예약</h2><p>로그인 후 병원 상세에서 날짜와 시간을 선택합니다. 신청 내용을 확인하고 확정하면 내 예약에 표시됩니다. 진료 30분 전까지 취소하면 포인트가 반환됩니다.</p>${link('reservations','내 예약 확인')}</section><section><h2>지난 진료와 후기</h2><p>완료된 본인의 진료만 평가할 수 있습니다. 네 가지 점수와 후기를 작성하면 병원 평점과 최근 후기에 반영됩니다.</p>${link('past','지난 진료 보기')}</section></div>`;
 return empty('메뉴에서 이용할 업무를 선택해주세요.');}
function boardForm(kind,r={}){return form(kind+'.save',`<input type="hidden" name="IDX" value="${r.IDX||''}">${input('TITLE','제목',r.TITLE||'','text','required')}${area('CONTENTS','내용',r.CONTENTS||'')}${kind==='notice'?input('FILE_NAME','첨부 파일명 (.txt)')+'<label>첨부 텍스트<textarea name="FILE_TEXT"></textarea></label>':''}`);}
function catalogForm(h={}){return form('catalog.save',`<input type="hidden" name="H_IDX" value="${h.H_IDX||''}">${['HOSP','MAJOR','ADDR','TEL','ONHOUR','OFFHOUR','ADDR_GPS'].map((k,i)=>input(k,['병원명','진료과','주소','전화번호','시작 시간 (0900)','종료 시간 (1800)','좌표 (위도,경도)'][i],h[k]||'')).join('')}<label>예약 접수<select name="REG_CHK"><option value="Y">가능</option><option value="N" ${h.REG_CHK==='N'?'selected':''}>중지</option></select></label>`);}
function act(action,p){if(navigator.locks)return navigator.locks.request('drher-state',()=>executeAct(action,p));return executeAct(action,p);}
function executeAct(action,p){error='';message='';try{if(action==='boardSearch'){selected={FILTER:p.FILTER};}else if(action==='detail'){selected=p;view='detail';}else if(action==='slots'){selected=p;view='booking';}else if(action==='search'){selected={search:p};view='search';}else if(action==='reviewForm'){selected=p;view='review';}else{const r=call(action,p);if(action==='book'&&r.code!==0)throw Error(r.message||'포인트 또는 중복 예약을 확인해주세요.');message=r&&r.message||'변경사항을 저장했습니다.';if(action==='login'||action==='logout'||action==='withdraw')view='search';if(action==='book'||action==='cancel')view='reservations';if(action==='rate')view='past';if(action==='register'||action==='resetPassword')view='accounts';if(action==='reset')view='search';}}catch(e){error=e.message;}render();}
function bind(){D.querySelectorAll('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();view=a.dataset.view;selected=null;error='';message='';history.replaceState(null,'','?view='+view);render();});D.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action,JSON.parse(b.dataset.values)));D.querySelectorAll('[data-command]').forEach(f=>f.onsubmit=e=>{e.preventDefault();act(f.dataset.command,Object.fromEntries(new FormData(f)));});const f=D.getElementById('avatar');if(f)f.onchange=()=>{const file=f.files[0];if(!file)return;if(file.size>200000||!['image/png','image/jpeg'].includes(file.type)){error='200KB 이하 PNG 또는 JPEG 파일을 선택해주세요.';render();return;}const reader=new FileReader();reader.onload=()=>act('avatar',{DATA:reader.result});reader.readAsDataURL(file);};}
render();})();
