import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';
const files=['fixtures.js','mock-backend.js','modules.js','workspace.js'];
function page(){const dom=new JSDOM('<div id="workspace"></div>',{url:'http://localhost/hospital/workspace/',runScripts:'outside-only'});for(const f of files)dom.window.eval(fs.readFileSync(new URL('../runtime/'+f,import.meta.url),'utf8'));return dom;}
test('all workspace modules render reachable forms and role errors without browser automation',()=>{const dom=page(),w=dom.window,d=w.document;const views=['search','reservations','past','favorites','profile','points','notice','faq','qna','guide','accounts','register','recover','withdraw'];for(const view of views){const a=d.createElement('a'); // select real navigation whenever available; account views use new page URL
 if(d.querySelector('[data-view="'+view+'"]'))d.querySelector('[data-view="'+view+'"]').click();else{w.history.replaceState(null,'','?view='+view);w.eval(fs.readFileSync(new URL('../runtime/workspace.js',import.meta.url),'utf8'));}
 assert.ok(d.querySelector('h1'));assert.ok(d.querySelector('#content').textContent.trim().length>0,view);assert.equal(d.querySelectorAll('a[href="#"]').length,0);for(const input of d.querySelectorAll('input:not([type=hidden]),select,textarea'))assert.ok(input.closest('label'),view+' label');}
 w.DrHerWorkspace.backend.execute('login',{ID:'admin',PWD:'DemoPass123!'});w.history.replaceState(null,'','?view=admin');w.eval(fs.readFileSync(new URL('../runtime/workspace.js',import.meta.url),'utf8'));assert.match(d.querySelector('#content').textContent,/예약 관리/);assert.ok(d.querySelector('[data-view="catalog"]'));dom.window.close();});
test('workspace forms persist FAQ across administrator/member switch and show inline errors',()=>{const dom=page(),w=dom.window,d=w.document;w.DrHerWorkspace.backend.execute('login',{ID:'admin',PWD:'DemoPass123!'});w.history.replaceState(null,'','?view=faq');w.eval(fs.readFileSync(new URL('../runtime/workspace.js',import.meta.url),'utf8'));const form=d.querySelector('form[data-command="faq.save"]');form.elements.TITLE.value='합성 FAQ';form.elements.CONTENTS.value='실행된 새 답변';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.match(d.querySelector('#content').textContent,/실행된 새 답변/);assert.match(d.querySelector('[role=status]').textContent,/저장/);dom.window.close();});
test('detail day strip uses real availability and booking keeps one visible summary',()=>{const dom=page(),w=dom.window,d=w.document,b=w.DrHerWorkspace.backend;b.execute('login',{ID:'demo',PWD:'DemoPass123!'});w.history.replaceState(null,'','?view=search');w.eval(fs.readFileSync(new URL('../runtime/workspace.js',import.meta.url),'utf8'));
 const chips=[...d.querySelectorAll('.major-filter .filter-chip')];assert.ok(chips.length>1,'department filters from catalog');chips.find(c=>c.textContent.includes('내과')).click();assert.ok([...d.querySelectorAll('.hospital-row')].every(r=>r.textContent.includes('내과')),'department filter narrows results');
 d.querySelector('[data-action="detail"]').click();assert.ok(d.querySelector('.doctors li'),'existing DOC_COMM shown');assert.match(d.querySelector('.lede').textContent,/가상/);
 const days=[...d.querySelectorAll('.day-strip .day')];assert.equal(days.length,8);const open=days.find(x=>!x.disabled);const {H_IDX,DATE}=JSON.parse(open.dataset.values);const [year,month,day]=DATE.split('-');const expected=b.execute('times',{H_IDX,year,month,day}).length;assert.match(open.textContent,new RegExp(expected+'개'));
 open.click();const slots=[...d.querySelectorAll('input[name=RESERV2]')];assert.equal(slots.length,expected);assert.ok(slots.every(s=>s.closest('label')));slots[0].checked=true;slots[0].dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('[data-summary-time]').textContent,slots[0].value);
 d.querySelector('form[data-command="book"]').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.ok(d.querySelector('.visit-row .date-block'),'reservation listed with date block');assert.equal(b.execute('reservations').at(-1).RESERV2,slots[0].value);
 b.execute('login',{ID:'admin',PWD:'DemoPass123!'});w.history.replaceState(null,'','?view=admin');w.eval(fs.readFileSync(new URL('../runtime/workspace.js',import.meta.url),'utf8'));const pending=w.DrHerWorkspace.backend.execute('state').admin.reservations.filter(r=>r.DEL_CHK==='B').length;assert.match(d.querySelector('.admin-counts').textContent,new RegExp('예정 예약'+pending+'건'));dom.window.close();});
// Complete built page: real <script src> order from the source shell, then header navigation and detail clicks.
async function builtPage(locks){const {ResourceLoader}=await import('jsdom');const dist=new URL('../dist/',import.meta.url);class Local extends ResourceLoader{fetch(url){return Promise.resolve(fs.readFileSync(new URL('.'+new URL(url).pathname,dist)));}}const store=new Map();const dom=new JSDOM(fs.readFileSync(new URL('hospital/workspace/index.html',dist),'utf8'),{url:'http://127.0.0.1:54516/hospital/workspace/',resources:new Local(),runScripts:'dangerously',beforeParse(w){Object.defineProperty(w,'localStorage',{value:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)}});if(locks)Object.defineProperty(w.navigator,'locks',{value:locks});}});for(let i=0;i<100&&!dom.window.document.querySelector('.service-nav');i++)await new Promise(r=>setTimeout(r,20));return dom;}
const tick=ms=>new Promise(r=>setTimeout(r,ms));
test('built workspace page binds header navigation and detail with a working lock',async()=>{const dom=await builtPage({request:(name,opts,cb)=>Promise.resolve().then(typeof opts==='function'?opts:cb)});const d=dom.window.document;assert.equal(d.querySelector('h1').textContent,'병원 찾기');const b=[...d.querySelectorAll('[data-action=detail]')].find(x=>JSON.parse(x.dataset.values).H_IDX==10);b.click();await tick(20);assert.ok(d.querySelector('.day-strip'),'detail opened');d.querySelector('.service-nav [data-view=reservations]').click();assert.equal(d.querySelector('h1').textContent,'내 예약');dom.window.close();});
test('a lock that never resolves cannot freeze view navigation, and a blocked write fails visibly',async()=>{const dom=await builtPage({request:(name,opts)=>new Promise((_,reject)=>opts&&opts.signal&&opts.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'}))))});const d=dom.window.document;const favBefore=dom.window.DrHerWorkspace.backend.execute('favorites').length;[...d.querySelectorAll('[data-action=detail]')][0].click();await tick(20);assert.ok(d.querySelector('.day-strip'),'view-only detail does not wait on the write lock');d.querySelector('[data-action=favorite]').click();await tick(4300);assert.match(d.querySelector('[role=alert]').textContent,/다른 창에서 변경 사항을 저장하는 중/);assert.equal(dom.window.DrHerWorkspace.backend.execute('favorites').length,favBefore,'no write without the lock');dom.window.close();});
